name: Create Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [i386, amd64]
        include:
          - architecture: i386
            build-arch: x86
            build-name: i386-windows
          - architecture: amd64
            build-arch: x64
            build-name: amd64-windows

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          architecture: ${{ matrix.build-arch }}
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
          pip install pyinstaller

      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: Build the executable
        run: |
          pyinstaller .\src\main.py -cDF -n ${{ github.event.repository.name }} `
            --collect-all selenium --collect-all inquirer --copy-metadata readchar

      - name: Download and extract 7zip binaries
        run: |
          curl -o 7z2501-extra.7z https://www.7-zip.org/a/7z2501-extra.7z
          if ("${{ matrix.architecture }}" -eq "x86") {
            7z e 7z2501-extra.7z -odist/bin/7zip 7z*.*
          } else {
            7z e 7z2501-extra.7z -odist/bin/7zip x64/7z*.*
          }

      - name: Package into zip
        run: |
          cd .\dist\
          7z a ${{ github.event.repository.name }}.${{ matrix.build-name }}.zip * -mx9

      - name: Upload updater artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}.${{ matrix.architecture }}
          path: dist/${{ github.event.repository.name }}.${{ matrix.build-name }}.zip

  draft-release:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/
          merge-multiple: true

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/*
          draft: true